name: deploy
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: TEMP2=$(mktemp)
      - run: echo "${{ secrets.KEY }}" > $TEMP2
      - run: ssh -o 'StrictHostKeyChecking no' -i $TEMP2 ${{ secrets.USERNAME }}@${{ secrets.HOST }} whoami
#    - run: echo ${{ secrets.KEY }} > key.txt
#    - run: chmod 700 key.txt
#    - run: ssh -i key.txt ${{ secrets.USERNAME }}@${{ secrets.HOST }} whoami
#    - run: rm key.txt

#    - name: executing remote ssh commands using key
#      uses: appleboy/ssh-action@v0.1.4
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        key: ${{ secrets.KEY }}
#        port: ${{ secrets.PORT }}
#        script: whoami